//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poduska.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merch()
        {
            this.sostav = new HashSet<sostav>();
        }
        public string DiscountText
        {
            get
            {
                return Convert.ToBoolean(discount) ? "Есть скидка" : "Скидка отсутствует";
            }
        }
        public bool TextColor
        {
            get
            {
                if (Convert.ToDouble(discount) != 0) return true;
                else return false;
            }
        }
        public string Arrow
        {
            get
            {
                if (TextColor) return "Strikethrough";
                else return "None";
            }
        }
        public string newcost
        {
            get
            {
                if (TextColor) return Convert.ToString((Convert.ToDouble(prise)) - Convert.ToDouble(prise) * Convert.ToDouble(discount) / 100); else return "";
            }
        }

        public int id { get; set; }
        public string photo { get; set; }
        public string name { get; set; }
        public string dexcription { get; set; }
        public string manufacture { get; set; }
        public int prise { get; set; }
        public Nullable<int> discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sostav> sostav { get; set; }
    }
}
